name: Build and Deploy to GKE

# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:  
    inputs:
      zone:
        description: 'GKE Cluster Zone'
        required: true
      cluster_name:
        description: 'GKE Cluster Name'
        required: true
      project_id:
        description: 'GCP Project ID'
        required: true

env:
  GKE_CLUSTER: ${{ github.event.inputs.cluster_name }}
  GKE_ZONE: ${{ github.event.inputs.zone }}
  PROJECT_ID: ${{ github.event.inputs.project_id }}

# env:
#   PROJECT_ID: ${{ secrets.GKE_PROJECT }}
#   GKE_CLUSTER: cluster-1    # Add your cluster name here.
#   GKE_ZONE: us-central1-c   # Add your cluster zone here.
  

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authorize GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json:  ${{ secrets.GCP_SA_KEY }}

    # Deploy the Docker image to the GKE cluster
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: |
        gcloud info
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }} --project ${{ env.PROJECT_ID }}
    - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GCP_SA_KEY }}
  
    - name: Deploy
      run: |
        
        kubectl get pods

        # ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        # ./kustomize build . | kubectl apply -f -
        # kubectl rollout status deployment/$DEPLOYMENT_NAME
        # kubectl get services -o wide
